from tkinter import *
win = Tk()
win.title("지갑지킴이 UI 디자인")
win.geometry("400x500")
Label(win, text="날짜 (YYYY-MM-DD)").grid(row=0, column=0)
entry_date = Entry(win, width=20)
entry_date.grid(row=0, column=1)
Label(win, text="카테고리").grid(row=1, column=0)
entry_category = Entry(win, width=20)
entry_category.grid(row=1, column=1)
Label(win, text="금액").grid(row=2, column=0)
entry_amount = Entry(win, width=20)
entry_amount.grid(row=2, column=1)
btn_add = Button(win, text="추가", width=10)
btn_clear = Button(win, text="기록 초기화", width=10)
btn_save = Button(win, text="TXT 저장", width=10)
btn_load = Button(win, text="TXT 불러오기", width=10)
btn_add.grid(row=3, column=0)
btn_clear.grid(row=3, column=1)
btn_save.grid(row=4, column=0)
btn_load.grid(row=4, column=1)
listbox_records = Listbox(win, width=50, height=25)
listbox_records.grid(row=5, column=0, columnspan=2)
win.mainloop()

